### ISSUE TITLE
Serverneustart

### ISSUE THREAD

**Issue by xXMcpeGamerXx03** [LucDevOffical/AdminUI#1]
Na, dein AdminUI ist nicht so gut.
Es gibt nur 3 Sachen die man machen kann.
Wow

**Comment by LucDevOffical** [comment]
Hey,

danke für dein Feedback. Ich bitte dich, dies ist nur für Leute gedacht die ein Restart-Skript haben. Zudem ist der Button InGame nun Server-Stop :) 

Es werden Updates folgen und ja ich habe gesehen wie du deine Nachricht geupdatet hast.

Ich wünsche dir noch einen schönen Abend!

Mit freundlichen Grüßen

Luca Emilio Wilms

**Comment by LucDevOffical** [comment]
PS: Man hätte dies über eine kurze Nachreicht in Erfahrung bringen können.

**Comment by LucDevOffical** [comment]
Ich habe mir mal dein Profil angeschaut, die meisten Sachen sind nur geforked und nicht selber programmiert. Schade aber auch :(

**Comment by LucDevOffical** [comment]
Achso, ich kann dir gerne mal ausschnitte aus meiner ServerAPI für Spigot/Bungeecord mit NoSQL Support (MongoDB & Redis).

Mir ist selber klar, das diese UI sehr simpel gehalten ist, jedoch hat dies auch einen Grund. Ich hatte Langeweile und habe innerhalb von 45 Minuten irgendwas dahin geschrieben. Wenn gewollt werde ich Updates programmieren und alles über eine Config nutzbar machen.

**Comment by xXMcpeGamerXx03** [comment]
Was hat mein Github Profil damit zutun?
Außerdem stelle ich jetzt nicht viel auf Github weil das meiste einfach Privat ist oder ich das für Server programmiere.
Und es juckt mich nicht was in deiner ServerAPI drin ist.

**Comment by LucDevOffical** [comment]
Wie bereits gesagt es wird noch Updates geben. Kein böses Blut :) Darf man wissen für welche Server Du programmierst?

BTW. Meine Projekte sind auch zu 90% Privat und nur kleine einfache Sachen veröffentlichte ich :)

**Comment by xXMcpeGamerXx03** [comment]
Warum möchtest du wissen für welche/n Server ich programmiere?

**Comment by LucDevOffical** [comment]
> Warum möchtest du wissen für welche/n Server ich programmiere?

Aus reinem Interesse.

**Comment by LucDevOffical** [comment]
Selbstverständlich musst es du es nicht beantworten:)
